# MongoDB Secret
apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: dev
  labels:
    app: mongodb
type: Opaque
data:
  MONGO_USERNAME: YWRtaW4=                  # Base64: admin
  MONGO_PASSWORD: cGFzc3dvcmQxMjM=          # Base64: password123
